export interface Order {
    "orderID": number,
    "customerID": string,
    "employeeID": number,
    "orderDate": Date,
    "requiredDate": Date,
    "shippedDate": Date,
    "shipVia": number,
    "freight": number,
    "shipName": string,
    "shipAddress": string,
    "shipCity": string,
    "shipRegion": string | null,
    "shipPostalCode": string,
    "shipCountry": string,
}
